### ISSUE TITLE
stream was reset: NO_ERROR

### ISSUE THREAD

**Issue by john1jan** [joltup/react-native-fetch-blob#82]
Hi ! Thank you for reporting an issue, but we would like to remind you, we have a trouble shooting page in our wiki. 
You may want to take a look on that page oGetting this error while uploading a video of size 30mb

     RNFetchBlob.fetch('POST', "https://apiendpoint.com/uploadvideo", {
                        // dropbox upload headers
                        ...this.props.header,
                        'Content-Type': 'multipart/form-data',
                        // Change BASE64 encoded data to a file path with prefix `RNFetchBlob-file://`.
                        // Or simply wrap the file path with RNFetchBlob.wrap().
                    }, [
                            // element with property `filename` will be transformed into `file` in form data

                            { name: 'file', filename: 'vid.mp4', data: RNFetchBlob.wrap(response.uri) },
                            // custom content type

                        ]).then((res) => {
                        })
                        .catch((err) => {
                            console.log("video upload failed",err)
                        })
```

Getting this stack trace 

okhttp3.internal.http2.StreamResetException: stream was reset: NO_ERROR
W/System.err:     at okhttp3.internal.http2.Http2Stream.checkOutNotClosed(Http2Stream.java:567)
W/System.err:     at okhttp3.internal.http2.Http2Stream$FramingSink.emitFrame(Http2Stream.java:501)
W/System.err:     at okhttp3.internal.http2.Http2Stream$FramingSink.write(Http2Stream.java:481)
W/System.err:     at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
W/System.err:     at okio.RealBufferedSink.write(RealBufferedSink.java:91)
W/System.err:     at com.RNFetchBlob.RNFetchBlobBody.pipeStreamToSink(RNFetchBlobBody.java:268)
W/System.err:     at com.RNFetchBlob.RNFetchBlobBody.writeTo(RNFetchBlobBody.java:119)
W/System.err:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:59)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at com.RNFetchBlob.RNFetchBlobReq$1.intercept(RNFetchBlobReq.java:318)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at com.RNFetchBlob.RNFetchBlobReq$2.intercept(RNFetchBlobReq.java:326)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:129)
W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/ReactNativeJS: stream was reset: NO_ERROR
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W/System.err:     at java.lang.Thread.run(Thread.java:764)
V/MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null
W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
D/RNBranch: onInitFinished
D/RNBranch: sendRNEvent
D/RNBranch: Catalyst instance poller try 1
D/RNBranch: Catalyst instance active
W/GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
W/MediaPlayerNative: info/warning (3, 0)
W/GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
W/GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
W/ReactNativeJS: stream was reset: NO_ERROR
W/System.err: okhttp3.internal.http2.StreamResetException: stream was reset: NO_ERROR
W/System.err:     at okhttp3.internal.http2.Http2Stream.checkOutNotClosed(Http2Stream.java:567)
W/System.err:     at okhttp3.internal.http2.Http2Stream$FramingSink.emitFrame(Http2Stream.java:501)
W/System.err:     at okhttp3.internal.http2.Http2Stream$FramingSink.write(Http2Stream.java:481)
W/System.err:     at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
W/System.err:     at okio.RealBufferedSink.write(RealBufferedSink.java:91)
W/System.err:     at com.RNFetchBlob.RNFetchBlobBody.pipeStreamToSink(RNFetchBlobBody.java:268)
W/System.err:     at com.RNFetchBlob.RNFetchBlobBody.writeTo(RNFetchBlobBody.java:119)
W/System.err:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:59)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at com.RNFetchBlob.RNFetchBlobReq$1.intercept(RNFetchBlobReq.java:318)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at com.RNFetchBlob.RNFetchBlobReq$2.intercept(RNFetchBlobReq.java:326)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:129)
W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W/System.err:     at java.lang.Thread.run(Thread.java:764)
W/System.err: okhttp3.internal.http2.StreamResetException: stream was reset: NO_ERROR
W/ReactNativeJS: stream was reset: NO_ERROR
W/System.err:     at okhttp3.internal.http2.Http2Stream.checkOutNotClosed(Http2Stream.java:567)
W/System.err:     at okhttp3.internal.http2.Http2Stream$FramingSink.emitFrame(Http2Stream.java:501)
W/System.err:     at okhttp3.internal.http2.Http2Stream$FramingSink.write(Http2Stream.java:481)
W/System.err:     at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
W/System.err:     at okio.RealBufferedSink.write(RealBufferedSink.java:91)
W/System.err:     at com.RNFetchBlob.RNFetchBlobBody.pipeStreamToSink(RNFetchBlobBody.java:268)
W/System.err:     at com.RNFetchBlob.RNFetchBlobBody.writeTo(RNFetchBlobBody.java:119)
W/System.err:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:59)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at com.RNFetchBlob.RNFetchBlobReq$1.intercept(RNFetchBlobReq.java:318)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at com.RNFetchBlob.RNFetchBlobReq$2.intercept(RNFetchBlobReq.java:363)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:129)
W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W/System.err:     at java.lang.Thread.run(Thread.java:764)

r find issues tagged "trouble shooting" :p 

* please provide the version of installed library and RN project.
* a sample code snippet/repository is very helpful to spotting the problem.
* issues which have been tagged as 'needs feedback', will be closed after 2 weeks if receive no feedbacks.
* issues lack of detailed information will be closed without any feedback

**Comment by Traviskn** [comment]
Your upload code looks correct, we may need to investigate a bit more to reproduce and figure out why the error is occurring.  Would you be able to share your version of rn-fetch-blob, react-native, and the type of device you are getting this error on?

**Comment by KashmitAI** [comment]
I get the same error, i'm using react-native-image-crop-picker to pick a video and then this to upload a form data with data and the file. The body looks like this:
          { name: 'title', data: title },
          { name: 'description', data: description },
          { name: 'file', filename: 'video.mp4', type: file.mime, data: RNFetchBlob.wrap(file.path) }
And the file object looks like:
height: 1920
mime: "video/mp4"
modificationDate: "1547732405000"
path: "file:///data/user/0/com.app/cache/react-native-image-crop-picker/VID_20181018_052022.mp4"
size: 545178067
width: 1080
The versions i'm using are RN: 0.57.8 and rn-fetch-blob: 0.10.15

**Comment by BagasNS** [comment]
i was facing same error, in my case my server using nginx and reserve to node js (express), i found that nginx default config for `client_max_body_size 1M`, i add this line to /etc/nginx/nginx.conf `client_max_body_size 0;` and the problem is solve.
see here for more https://serverfault.com/questions/401729/uploading-files-greater-than-1mb-connection-resets
